// TRAIN TOKENS
export const TRAIN_REPOSITORY_TOKEN = 'TRAIN_REPOSITORY_TOKEN';
export const TRAIN_SERVICE_TOKEN = 'TRAIN_SERVICE_TOKEN';
export const SEEDING_TRAIN_SERVICE_TOKEN = 'SEEDING_TRAIN_SERVICE_TOKEN';

// POINT TOKENS
export const POINT_SERVICE_TOKEN = 'POINT_SERVICE_TOKEN';
export const POINT_REPOSITORY_TOKEN = 'POINT_REPOSITORY_TOKEN';
export const SEEDING_POINT_SERVICE_TOKEN = 'SEEDING_POINT_SERVICE_TOKEN';

// TRAIN SCHEDULE TOKENS
export const TRAIN_SCHEDULE_SEEDING_SERVICE_TOKEN =
  'TRAIN_SCHEDULE_SEEDING_SERVICE_TOKEN';
export const TRAIN_SCHEDULE_SERVICE_TOKEN = 'TRAIN_SCHEDULE_SERVICE_TOKEN';
export const TRAIN_SCHEDULE_REPOSITORY_TOKEN =
  'TRAIN_SCHEDULE_REPOSITORY_TOKEN';
